version: '3' 
services:
    postgres:
        image: 'postgres:latest'
        environment: 
          - POSTGRES_PASSWORD=postgres_password
          - POSTGRES_USERNAME=postgres
          - POSTGRES_DB=simple_blog_api
    api:
        depends_on:
            - postgres
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - 3000:3000
        environment:
            - POSTGRES_USERNAME=postgres
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=simple_blog_api
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_PORT=5432
